### ISSUE TITLE
[Bug] Resource parameters on getUserPermissions method do not work

### ISSUE THREAD

**Issue by jonas-at-uneti** [permitio/permit-node#60]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The `resources` and `resource_types` filter do not work for the `getUserPermissions` method.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

The interface `IGetUserPermissionsInput` is not defined correctly and also not used to check typing in `enforcer.ts`.
Fix:

`src/enforcement/interfaces.ts` line 18-23
```ts
export interface IGetUserPermissionsInput {
  user: IUser;
  tenants?: string[];
  resources?: string[];
  resource_types?: string[];
}
```

`src/enforcement/enforcer.ts` line 171-176
```ts
const input: IGetUserPermissionsInput = {
  user: isString(user) ? { key: user } : user,
  tenants,
  resources,
  resource_types,
};
```

And adding a simple extra test:
`rbac.e2e.spec.ts`
```ts
logger.info('testing get user permissions with resource types parameter set');
userPermissions = await permit.getUserPermissions(user.key, undefined, undefined, [
  'nonExistingResource',
]);
t.is(Object.keys(userPermissions).length, 0);
```

**Comment by asafc** [comment]
opened internal ticket on @omer9564 

https://linear.app/permit/issue/PER-8247/fix-issue-with-get-user-permissions-resource-filter-this-is-probably-a

**Comment by asafc** [comment]
Update:
Found the issue - it's actually not in the SDK - but in the PDP. A fix is currently being reviewed.
Will close this ticket once the fix has been deployed and verified.
