### ISSUE TITLE
Error when importing lib in Next 14

### ISSUE THREAD

**Issue by jeremyrx7** [permitio/permit-node#76]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I am getting below error, while integrating this with Nextjs14:
<img width="829" alt="image" src="https://github.com/permitio/permit-node/assets/160863762/b05c21c0-dfee-4a8f-8282-047f8c50b43a"> 
Any idea why? This is the snippet:

```
> 4 | const permit = new Permit({ token: process.env.PERMIT_IO_API_KEY });

```

As a standalone js file that syncs resources works fine.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- Nextjs14

**Comment by obsd** [comment]
Fixed in version 2.4.1.
Thanks for reporting.
