### ISSUE TITLE
UserRead type does not contain all api fields

### ISSUE THREAD

**Issue by Akkuma** [permitio/permit-node#91]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
https://github.com/permitio/permit-node/blob/main/src/openapi/types/user-read.ts
https://api.permit.io/v2/redoc#tag/Users/operation/get_user

There are fields missing that the API says exists and shows returned.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by obsd** [comment]
Hi @Akkuma 
Here is the CR that should fix it, let me know if that what you had in mind

https://github.com/permitio/permit-node/pull/93
